### ISSUE TITLE
[Possible Bug] checksum.txt conflicts

### ISSUE THREAD

**Issue by unbirthdays** [ServiceNowDevProgram/Plants#214]
Hi.

I see that a lot of these pull requests are having conflicts with checksum.txt files. I noticed that there's a `checksum.txt` in the repo, but it is not properly ignoring these files. I think the issue is because it's not looking in subdirectories for the `checksum.txt` files. 

A possible solution would be to change the `checksum.gitignore` contents from 
```
checksum.txt
```
to 
```
**/checksum.txt
```

Let me know if this could be a solution or if this was intentional!

Thanks.

**Comment by sharsha315** [comment]
Hi @unbirthdays, I would like to work on this issue. Could you please guide to get started. Thank you.

**Comment by SapphicFire** [comment]
The documentation behind this behaviour and why can be found here:
- [ServiceNow Docs: Source Control Integration](https://docs.servicenow.com/bundle/xanadu-application-development/page/build/applications/concept/c_SourceControlIntegration.html#d246033e163)
- [ServiceNow Docs: Move application files in a Git repository](https://docs.servicenow.com/bundle/xanadu-application-development/page/build/app-engine-studio/task/source-control-move-files-git.html)
- [ServiceNow Developer: GitHub Guide - Checksum Issues](https://developer.servicenow.com/dev.do#!/guides/xanadu/developer-program/github-guide/troubleshooting-github-issues#checksum-issues)

The .gitignore file also seems to be a template because normally these do not have a prefix. This should be addressable
